# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yh' blog
email: yangaov119@126.com
description: "This is Yh's blog"
baseurl: /blog
url: "http://blog.yhao.me" # the base hostname & protocol for your site

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
